from __future__ import annotations

import json
import logging
import os
import time
from typing import Any

from pydantic import BaseModel, Field

from app.aegis_ast_validation_sandbox import AegisASTValidationSandbox, AegisValidationResult
from app.text import SandboxRequest, SandboxResult, execute_in_sandbox

logger = logging.getLogger("software_factory")


class FactoryPipelineRequest(BaseModel):
    tool_code: str = Field(..., description="Raw Python code generated by Manus/Ralph5.")
    test_code: str = Field(..., description="Pytest validation test cases.")
    target_file: str = Field(..., description="Target repository path for the module.")
    timeout_seconds: int = Field(default=5)
    memory_limit_mb: int = Field(default=256)


class FactoryPipelineResult(BaseModel):
    status: str = Field(..., description="'PROMOTED', 'REJECTED_AST', 'REJECTED_SANDBOX'")
    patch_hash: str
    ast_report: dict[str, Any]
    sandbox_report: dict[str, Any] | None = None
    ledger_hash: str | None = None
    timestamp: float


class SoftwareFactoryPipeline:
    def __init__(self, ledger_spine_path: str = "sail_event_spine.jsonl"):
        self.ledger_path = ledger_spine_path
        self._ensure_ledger()

    def _ensure_ledger(self) -> None:
        if not os.path.exists(self.ledger_path):
            with open(self.ledger_path, "w", encoding="utf-8") as handle:
                genesis = {"event": "FACTORY_GENESIS", "timestamp": time.time(), "block_hash": "0" * 64}
                handle.write(json.dumps(genesis) + "\n")

    def _get_last_hash(self) -> str:
        try:
            with open(self.ledger_path, "r", encoding="utf-8") as handle:
                lines = [line.strip() for line in handle.readlines() if line.strip()]
            if not lines:
                return "0" * 64
            return json.loads(lines[-1]).get("block_hash", "0" * 64)
        except Exception:
            return "0" * 64

    def _commit_to_gold_ledger(self, payload: dict[str, Any]) -> str:
        import hashlib
        import hmac

        prev_hash = self._get_last_hash()
        canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"))
        hsm_key = os.getenv("SYNAPSE_HSM_KEY", "HARDWARE_ENCLAVE_SECRET_KEY").encode("utf-8")
        block_hash = hmac.new(hsm_key, (prev_hash + canonical).encode("utf-8"), hashlib.sha256).hexdigest()
        block = {"block_hash": block_hash, "previous_hash": prev_hash, "payload": payload, "timestamp": time.time()}

        with open(self.ledger_path, "a", encoding="utf-8") as handle:
            handle.write(json.dumps(block) + "\n")
        return block_hash

    def execute_pipeline(self, request: FactoryPipelineRequest) -> FactoryPipelineResult:
        logger.info("🏭 [FACTORY] Processing build request for target: %s", request.target_file)
        ast_result: AegisValidationResult = AegisASTValidationSandbox.validate_patch_code(
            patch_code=request.tool_code,
            target_file=request.target_file,
        )

        if not ast_result.ok:
            logger.warning("🛑 [FACTORY HALT] AST Validation failed for %s.", request.target_file)
            return FactoryPipelineResult(
                status="REJECTED_AST",
                patch_hash=ast_result.patch_hash,
                ast_report=ast_result.to_dict(),
                timestamp=time.time(),
            )

        sandbox_req = SandboxRequest(
            tool_code=request.tool_code,
            test_code=request.test_code,
            timeout_seconds=request.timeout_seconds,
            memory_limit_mb=request.memory_limit_mb,
            network_allowed=False,
        )
        sandbox_res: SandboxResult = execute_in_sandbox(sandbox_req)
        if not sandbox_res.passed:
            logger.warning("🛑 [FACTORY HALT] Sandbox execution failed. Reason: %s", sandbox_res.failure_type)
            return FactoryPipelineResult(
                status="REJECTED_SANDBOX",
                patch_hash=ast_result.patch_hash,
                ast_report=ast_result.to_dict(),
                sandbox_report=sandbox_res.model_dump(),
                timestamp=time.time(),
            )

        ledger_payload = {
            "action": "PROMOTE_MODULE",
            "target_file": request.target_file,
            "patch_hash": ast_result.patch_hash,
            "runtime_ms": sandbox_res.runtime_ms,
            "status": "VERIFIED_GOLD",
        }
        ledger_hash = self._commit_to_gold_ledger(ledger_payload)
        logger.info("🏆 [FACTORY SUCCESS] Module promoted and anchored to Gold Ledger: %s...", ledger_hash[:16])
        return FactoryPipelineResult(
            status="PROMOTED",
            patch_hash=ast_result.patch_hash,
            ast_report=ast_result.to_dict(),
            sandbox_report=sandbox_res.model_dump(),
            ledger_hash=ledger_hash,
            timestamp=time.time(),
        )
